//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterDefaultBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterDefaultBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Better Default Browser ähnelt.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtering settings ähnelt.
        /// </summary>
        public static string BoxFilteringSettings {
            get {
                return ResourceManager.GetString("BoxFilteringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General settings ähnelt.
        /// </summary>
        public static string BoxGeneralSettings {
            get {
                return ResourceManager.GetString("BoxGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- Created with Ai-&gt;XAML Export Plug-In Version 0.2 (PC/64) --&gt;
        ///&lt;!-- By Mike Swanson (http://blog.mikeswanson.com/)           --&gt;
        ///
        ///&lt;Viewbox Width=&quot;14.000&quot; Height=&quot;10.000&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///&lt;Canvas Width=&quot;14.000&quot; Height=&quot;10.000&quot;&gt;
        ///
        ///  &lt;Canvas&gt;
        ///
        ///  &lt;!-- Ebene 1/&lt;Zusammengesetzter Pfad&gt; --&gt;
        ///  &lt;Path Fill=&quot;#ff000000&quot; Data=&quot;F1 M 4.500,0.000 L 0.000,5.000 L 4.500,10.000 L 6.000,8.500 L 2.500,5.000  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- Created with Ai-&gt;XAML Export Plug-In Version 0.2 (PC/64) --&gt;
        ///&lt;!-- By Mike Swanson (http://blog.mikeswanson.com/)           --&gt;
        ///
        ///&lt;Viewbox Width=&quot;16.000&quot; Height=&quot;12.000&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///&lt;Canvas Width=&quot;16.000&quot; Height=&quot;12.000&quot;&gt;
        ///
        ///  &lt;Canvas&gt;
        ///
        ///  &lt;!-- Ebene 1/&lt;Zusammengesetzter Pfad&gt; --&gt;
        ///  &lt;Path Fill=&quot;#ff000000&quot; Data=&quot;F1 M 10.000,6.000 C 10.000,7.110 9.110,8.000 8.000,8.000 C 6.890,8.000 6.0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string eye {
            get {
                return ResourceManager.GetString("eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- Created with Ai-&gt;XAML Export Plug-In Version 0.2 (PC/64) --&gt;
        ///&lt;!-- By Mike Swanson (http://blog.mikeswanson.com/)           --&gt;
        ///
        ///&lt;Viewbox Width=&quot;14.000&quot; Height=&quot;13.970&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///&lt;Canvas Width=&quot;14.000&quot; Height=&quot;13.970&quot;&gt;
        ///
        ///  &lt;Canvas&gt;
        ///
        ///  &lt;!-- Ebene 1/&lt;Zusammengesetzter Pfad&gt; --&gt;
        ///  &lt;Path Fill=&quot;#ff000000&quot; Data=&quot;F1 M 7.000,9.990 C 5.340,9.990 4.000,8.650 4.000,6.990 C 4.000,5.330 5.340 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string gear {
            get {
                return ResourceManager.GetString("gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browser ähnelt.
        /// </summary>
        public static string LabelBrowser {
            get {
                return ResourceManager.GetString("LabelBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string LabelFilterName {
            get {
                return ResourceManager.GetString("LabelFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        public static string LabelIsEnabled {
            get {
                return ResourceManager.GetString("LabelIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regex ähnelt.
        /// </summary>
        public static string LabelRegex {
            get {
                return ResourceManager.GetString("LabelRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
    }
}
